name: django-app

services:
  app:
    build: .
    container_name: app-container
    image: app-image
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - ./a_core:/app/a_core
      - ./a_home:/app/a_home
      - ./a_users:/app/a_users
      - ./static:/app/static
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
      - /app/.venv
    entrypoint: ["./entrypoint.sh"]
    command: ["./start.sh"]
    # command: ["sh", "-c", "ls -la /app && cat /app/start.sh && ./start.sh"]
    depends_on:
      - db

  db:
    image: postgres
    container_name: db-container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    container_name: celery-container
    image: app-image
    entrypoint: ["./entrypoint.sh"]
    command: ["celery", "-A", "a_core", "worker", "-E", "-l", "info"]
    volumes:
      - ./a_core:/app/a_core
      - ./a_home:/app/a_home
      - ./a_users:/app/a_users
      - ./static:/app/static
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
      - /app/.venv
    depends_on:
      - app
      - redis
      - db

  flower:
    image: app-image
    container_name: flower-container
    # entrypoint: ["./entrypoint.sh"]
    command: ["celery", "-A", "a_core", "flower", "--basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}"]
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis

  beat:
    image: app-image
    container_name: beat-container
    command: ["celery", "-A", "a_core", "beat", "-l", "INFO", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    volumes:
      - ./a_core:/app/a_core
      - ./a_home:/app/a_home
      - ./a_users:/app/a_users
      - ./static:/app/static
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
      - /app/.venv
    depends_on:
      - redis
      - app

volumes:
  postgres_data:
  redis_data: